apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tidd993yj-python
  janus-idp.io/tekton: tidd993yj-python
  backstage.io/kubernetes-id: tidd993yj-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tidd993yj-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
